### PR TITLE
v1.16.0

### PR DESCRIPTION
**Pull request by TheTrunk**
Remove prefork naming scheme from dashboard
Deletions of used login phrases
Hashes, repositories, zelids now live in zelflux repository
Bug fixes on UI
Prevent operations to of installation, removal to run at the same time
Prohibit  starting of app when app is in installation, removal process

TODOs:
Needs more testing
Testing of #278

### CODE REVIEW

**Comment by TheTrunk** [comment]
tack

**Comment by Cabecinha84** [comment]
Was #278 merged?

**Comment by TheTrunk** [comment]
It wasn't yet. I haven't yet tested those scripts - if you have a chance please test and report. I will perform tests asap

**Comment by Cabecinha84** [comment]
I believe those updates are the same he have put on his bashscript to update all daemons, if they weren't on the latest version. But I haven't tested on flux.

**Review by Cabecinha84 — APPROVED** [review]
Code review Ack. Did not had time to test it but changes looks small and ok. Also did not had time for test Kamil PR.

**Pull request merged**
