### PR TITLE
[Ready for Review] Updated instructions

### PR DESCRIPTION
**Pull request by fallengravity**
Hey, I've added better instructions for setting up ZelFlux. Right now I've only done Ubuntu and MongoDB install instructions - I will add CentOS & Zelcashd asap.

### CODE REVIEW

**Comment by milesmanley** [comment]
Awesome, thanks for your contributions. Looks good to me on first glance. Why did you decide to provide instructions for node v11? @fallengravity

**Comment by fallengravity** [comment]
A specific Node version wasn't mentioned, So I went off with version I've had the best experience with. When you use `nvm install 11` it automatically grabs the latest version 11 which at the moment is `v11.15.0` - We can simply change 11 to 12 if you've had better success with it 👍

**Comment by dk808** [comment]
@fallengravity Did you get this to work? I would figure installing curl would bork mongodb from past testing but also I do install mongodb using apt install. Also noticed it's missing the step to import the gpg key before updating. Will test this later to see if mongodb doesn't get borked by installing curl.

**Comment by fallengravity** [comment]
@dk808 I've never encountered that issue - We can always use wget if it's an issue, Thanks for pointing out the missing step! I will spin up a new VM and test it from start to finish again.

**Comment by fallengravity** [comment]
Ubuntu 16.04 setup (Removed the unneeded verbosity) :

```
root@vmi268413:~# wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -

OK

root@vmi268413:~# echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list

deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse

root@vmi268413:~# sudo apt-get update

root@vmi268413:~# sudo apt-get update
Hit:1 http://asi-fs-n.contabo.net/ubuntu xenial InRelease
Hit:2 http://asi-fs-n.contabo.net/ubuntu xenial-updates InRelease           
Hit:3 http://asi-fs-n.contabo.net/ubuntu xenial-backports InRelease         
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease           
Ign:5 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 InRelease
Hit:6 https://deb.nodesource.com/node_8.x xenial InRelease
Hit:7 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 Release
Get:8 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 Release.gpg [801 B]
Hit:9 https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease
Fetched 801 B in 2s (380 B/s)
Reading package lists... Done

root@vmi268413:~# sudo apt-get install -y mongodb-org

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libcurl3 mongodb-org-mongos mongodb-org-server mongodb-org-shell mongodb-org-tools
The following NEW packages will be installed:
  libcurl3 mongodb-org mongodb-org-mongos mongodb-org-server mongodb-org-shell mongodb-org-tools
0 upgraded, 6 newly installed, 0 to remove and 64 not upgraded.
Need to get 81.7 MB of archives.
After this operation, 272 MB of additional disk space will be used.

root@vmi268413:~# apt-get install curl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libcurl3-gnutls
The following packages will be upgraded:
  curl libcurl3-gnutls
2 upgraded, 0 newly installed, 0 to remove and 62 not upgraded.
Need to get 323 kB of archives.
After this operation, 2,048 B of additional disk space will be used.

root@vmi268413:~# curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

root@vmi268413:~# source ~/.profile

root@vmi268413:~# nvm install 11
Downloading and installing node v11.15.0...
Downloading https://nodejs.org/dist/v11.15.0/node-v11.15.0-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v11.15.0 (npm v6.7.0)
Creating default alias: default -> 11 (-> v11.15.0)

root@vmi268413:~# nvm use 11
Now using node v11.15.0 (npm v6.7.0)

root@vmi268413:~# systemctl start mongod

root@vmi268413:~# systemctl status mongod
● mongod.service - MongoDB Database Server
   Loaded: loaded (/lib/systemd/system/mongod.service; disabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-10-25 20:12:37 CEST; 5s ago

root@vmi268413:~# apt-get install git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.7.4-0ubuntu1.6).
0 upgraded, 0 newly installed, 0 to remove and 62 not upgraded.

root@vmi268413:~# git clone https://github.com/zelcash/zelflux
Cloning into 'zelflux'...

root@vmi268413:~# cd zelflux

root@vmi268413:~/zelflux# npm install

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

root@vmi268413:~/zelflux# sudo npm start

> zelflux@0.26.0 start /root/zelflux
> npm install && node init.js && (npm run zelfrontbuildwatch & npm run zelflux)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 33154 packages in 44.886s
found 0 vulnerabilities

? What is your ZelNodes IP address? 
```

**Pull request merged**
