### PR TITLE
v1.15.0

### PR DESCRIPTION
**Pull request by TheTrunk**
- Improvements on application volume creation using fallocate instead of dd resulting in very fast creation
- Creation of Confirmation Transaction in case of IP address changes. A restart of a node is needed for correct functionality.
- UI improvements
- Naming corrections to FluxNodes
- Kadena application version bump

This release is mandatory for Kadena operators to be applied before 6th of May.

### CODE REVIEW

**Review by Cabecinha84 — APPROVED** [review]
Ack

**Comment by Cabecinha84** [comment]
Please adjust our chainweb docker before release new kda docker image.
The healthy check should be adjusted the same way you did on the api to check if a node is synced.

**Comment by Cabecinha84** [comment]
And please also update kda bootstrap on flux servers. Thank you.

**Comment by TheTrunk** [comment]
both comments addressed

**Pull request merged**
